language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23

before_script:
 - cd MyApplication/  


#script: 
# - cd MyApplication/  
# - ./gradlew build connectedCheck
